# Bu, Render Blueprint'in DOĞRU ve GÜNCEL versiyonudur.

services:
  # 1. Mosquitto (MQTT) Servisi (Bu doğruydu, aynı kalıyor)
  - type: pserv
    name: mosquitto
    plan: free
    dockerImage: eclipse-mosquitto:2

  # 2. Teslamate Ana Uygulaması (HATALAR DÜZELTİLDİ)
  - type: web
    name: teslamate
    plan: free
    # DÜZELTME: 'image:' bloğu yerine doğru olan 'dockerImage' kullanılır.
    dockerImage: teslamate/teslamate:latest
    # DÜZELTME: 'port:' satırı SİLİNDİ.
    # Render, imajın içindeki EXPOSE 4000 komutunu otomatik olarak algılar.
    healthCheckPath: /
    envVars:
      - key: DATABASE_USER
        fromDatabase:
          name: teslamate-db
          property: user
      - key: DATABASE_PASS
        fromDatabase:
          name: teslamate-db
          property: password
      - key: DATABASE_NAME
        fromDatabase:
          name: teslamate-db
          property: database
      - key: DATABASE_HOST
        fromDatabase:
          name: teslamate-db
          property: host
      - key: MQTT_HOST
        value: mosquitto

  # 3. Grafana (Görselleştirme Paneli) (HATALAR DÜZELTİLDİ)
  - type: web
    name: grafana
    plan: free
    # DÜZELTME: 'image:' bloğu yerine doğru olan 'dockerImage' kullanılır.
    dockerImage: teslamate/grafana:latest
    # DÜZELTME: 'port:' satırı SİLİNDİ.
    # Render, imajın içindeki EXPOSE 3000 komutunu otomatik olarak algılar.
    healthCheckPath: /
    disk:
      name: grafana-data
      mountPath: /var/lib/grafana
      sizeGB: 1
    envVars:
      - key: GF_DATABASE_TYPE
        value: postgres
      - key: GF_DATABASE_HOST
        fromDatabase:
          name: teslamate-db
          property: host
      - key: GF_DATABASE_USER
        fromDatabase:
          name: teslamate-db
          property: user
      - key: GF_DATABASE_PASSWORD
        fromDatabase:
          name: teslamate-db
          property: password
      - key: GF_DATABASE_NAME
        value: grafana
