# Bu, Render Blueprint'in SON ve DOĞRU versiyonudur.

services:
  # 1. Mosquitto (MQTT) Servisi
  - type: pserv
    name: mosquitto
    plan: free
    image:
      url: eclipse-mosquitto:2

  # 2. Teslamate Ana Uygulaması
  - type: web
    name: teslamate
    plan: free
    image:
      url: teslamate/teslamate:latest
    healthCheckPath: /
    envVars:
      - key: DATABASE_USER
        fromDatabase:
          name: teslamate-db
          property: user
      - key: DATABASE_PASS
        fromDatabase:
          name: teslamate-db
          property: password
      - key: DATABASE_NAME
        fromDatabase:
          name: teslamate-db
          property: database
      - key: DATABASE_HOST
        fromDatabase:
          name: teslamate-db
          property: host
      - key: MQTT_HOST
        value: mosquitto

  # 3. Grafana (Görselleştirme Paneli)
  - type: web
    name: grafana
    plan: free
    image:
      url: teslamate/grafana:latest
    healthCheckPath: /
    disk:
      name: grafana-data
      mountPath: /var/lib/grafana
      sizeGB: 1
    envVars:
      - key: GF_DATABASE_TYPE
        value: postgres
      - key: GF_DATABASE_HOST
        fromDatabase:
          name: teslamate-db
          property: host
      - key: GF_DATABASE_USER
        fromDatabase:
          name: teslamate-db
          property: user
      - key: GF_DATABASE_PASSWORD
        fromDatabase:
          name: teslamate-db
          property: password
      - key: GF_DATABASE_NAME
        value: grafana
