# Bu, Render Blueprint'in GÜNCELLENMİŞ versiyonudur.
# Veritabanı MANUEL olarak oluşturulduktan sonra kullanılır.

services:
  # 1. Mosquitto (MQTT) Servisi
  - type: pserv
    name: mosquitto
    image:
      url: eclipse-mosquitto:2
    plan: free

  # 2. Teslamate Ana Uygulaması
  - type: web
    name: teslamate
    plan: free
    image:
      url: teslamate/teslamate:latest
    port: 4000
    healthCheckPath: /
    # Ortam Değişkenleri
    envVars:
      # Veritabanı bağlantı bilgilerini manuel oluşturduğumuz veritabanından al.
      - key: DATABASE_USER
        fromDatabase:
          name: teslamate-db # Manuel olarak oluşturduğunuz veritabanının adı
          property: user
      - key: DATABASE_PASS
        fromDatabase:
          name: teslamate-db
          property: password
      - key: DATABASE_NAME
        fromDatabase:
          name: teslamate-db
          property: database
      - key: DATABASE_HOST
        fromDatabase:
          name: teslamate-db
          property: host
      # MQTT sunucusunun adresini 'mosquitto' servisinin adresi olarak ayarla.
      - key: MQTT_HOST
        value: mosquitto

  # 3. Grafana (Görselleştirme Paneli)
  - type: web
    name: grafana
    plan: free
    image:
      url: teslamate/grafana:latest
    port: 3000
    healthCheckPath: /
    disk:
      name: grafana-data
      mountPath: /var/lib/grafana
      sizeGB: 1
    # Ortam Değişkenleri
    envVars:
      - key: GF_DATABASE_TYPE
        value: postgres
      - key: GF_DATABASE_HOST
        fromDatabase:
          name: teslamate-db # Manuel olarak oluşturduğunuz veritabanının adı
          property: host
      - key: GF_DATABASE_USER
        fromDatabase:
          name: teslamate-db
          property: user
      - key: GF_DATABASE_PASSWORD
        fromDatabase:
          name: teslamate-db
          property: password
      - key: GF_DATABASE_NAME
        value: grafana # Grafana kendi tabloları için bu ismi kullanır.
